language: php

env:
  - NETTE=default # 2.3 dev
  - NETTE=nette-2.3

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - php tests/travis/prepare-composer.php
  - composer self-update
  - composer install --no-interaction --prefer-source
  - vendor/bin/parallel-lint -e php --exclude vendor .

script: vendor/bin/phpunit --configuration tests/phpunit.xml tests
